### ISSUE TITLE
0.4.1 release Vinyl error

### ISSUE THREAD

**Issue by duluca** [fraserxu/gulp-html2js#20]
I'm getting the following error, when using gulp-html2js with the latest release. Upgraded from 0.3.1

```
\node_modules\gulp-html2js\node_modules\vinyl\index.js:120
    if (!this.path) throw new Error('No path specified! Can not get relative.');
                    ^

Error: No path specified! Can not get relative.
    at File.Object.defineProperty.get (\node_modules\gulp-html2js\node_modules\vinyl\index.js:120:27)
    at DestroyableTransform.bufferContents [as _transform] (\node_modules\gulp-concat\index.js:70:20)
    at DestroyableTransform.Transform._read (\node_modules\gulp-concat\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (\node_modules\gulp-concat\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (\node_modules\gulp-concat\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (\node_modules\gulp-concat\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (\node_modules\gulp-concat\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at PassThrough.ondata (_stream_readable.js:529:20)
    at emitOne (events.js:90:13)
    at PassThrough.emit (events.js:182:7)

```

**Comment by fraserxu** [comment]
Hi @duluca I'm guessing it's because this upgrade also changes the api(as it's from v0.3 to 0.4). Can you refer to the [usage section](https://github.com/fraserxu/gulp-html2js#usage) and check what changes you need to make to make your code work?

**Comment by duluca** [comment]
Thanks, I'll try out the angular adapter. For any breaking change, I'd recommend upping the major release version (per semver) so npm doesn't automatically update.

**Comment by fraserxu** [comment]
npm will only update when it's from `v0.3.1` to `v0.3.2` but not `v0.4.1`, no?

**Comment by duluca** [comment]
By default npm installs packages with ^, the behavior you're describing
happens with ~, which not many people bother to change. But furthermore
semver does describe the last number as a patch, second number for
non-breaking improvements and the first number for major breaking changes.
This why we are at Node 5.6.0 in less than a year :)

On Wed, Feb 17, 2016 at 6:15 PM Fraser Xu <notifications@github.com> wrote:

> npm will only update when it's from v0.3.1 to v0.3.2 but not v0.4.1, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fraserxu/gulp-html2js/issues/20#issuecomment-185452265>
> .
>
-- 
Best,

Doguhan Uluca
540-257-5143

**Comment by shuhei** [comment]
FYI, the rule is applied to `^` differently if the version is `0.x.x`.

https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by duluca** [comment]
Good to know. Thanks a bunch. Since then I've started using npm-shrinkwrap, it helps avoid surprises.

**Comment by shuhei** [comment]
@duluca I agree that npm-shrinkwrap works great for mission-critical systems. Anyway I noticed the breaking change at this issue. Thanks for opening it!

**Comment by ccravens** [comment]
Just in case this helps anyone in the future, I upgraded my gulp-html2js version and had to change how I used it from:

```
html2js({
          outputModuleName: 'templates'
        })
.concat('templates.js')
```

```
html2js('templates.js', {
          outputModuleName: 'templates'
        })
```
